import SessionProvider from "@/app/_providers/NextAuthProvider"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"
import NavBar from "@/shared/components/Navbar";
import { AppUIProvider } from "../_providers/AppUIProvider";
import {ChatProvider} from "@/app/_providers/ChatProvider"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WhatsApp",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html className="" lang="en">
      <body
        className={` overflow-hidden flex w-full h-screen ${geistSans.variable} ${geistMono.variable} min-h-screen text-primary-250 font-sans bg-[#171717]`}
      >
        <SessionProvider>
              <AppUIProvider>
                <ChatProvider>
                  <NavBar/>
                  {children}
                </ChatProvider>
              </AppUIProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
